# Generated by Django 4.2.7 on 2023-11-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=256, verbose_name='Запрос')),
                ('date', models.DateTimeField(verbose_name='Дата зароса')),
            ],
        ),
    ]
